#! /bin/sh

cp Multi-axisManipulatorSystem* /opt/Qt/apps -f
cp Base.fnc /opt/Qt/apps/records -f
cp ./WenQuanYi.ttf /opt/Qt/fonts
cp QtAutorun.sh /usr/bin -f
#cd 3a8
#cp -rf records subs sysconfig /mnt/database
#reboot
